### ISSUE TITLE
Connection Weirdness

### ISSUE THREAD

**Issue by killeand** [matzman666/PyPipboyApp#19] opened 2015-12-30 13:55 UTC
Hey, once in a while I'm getting this weird error that when I connect, it throws an exception from the Data Manager, but it still loads the GUI. Its easy to get around, as I just disconnect and try again and then it works. It might be due to a network hiccup, but then again I'm unsure. Here is the log:

libpng warning: iCCP: known incorrect sRGB profile
F1 2015-12-30 06:57:56,547 INFO Connecting to host 0.0.0.0:27000 Retry=False
F1 2015-12-30 06:57:56,554 DEBUG Connect to Host Thread started
F1 2015-12-30 06:57:56,799 INFO Successfully connected to 0.0.0.0:27000.
F1 2015-12-30 06:57:56,800 INFO Host Version: 1.2.37.0.
F1 2015-12-30 06:57:56,800 INFO Host Language: en.
F1 2015-12-30 06:57:56,800 DEBUG Starting receive thread.
F1 2015-12-30 06:57:56,801 DEBUG Received message with type 3 and size 590.
F1 2015-12-30 06:57:56,801 DEBUG Starting dispatch thread.
F1 2015-12-30 06:57:56,801 DEBUG Dispatching message with type 3 and size 590
F1 2015-12-30 06:57:56,804 INFO Connection State Changed: True - 0 - 
F1 2015-12-30 06:57:56,804 DEBUG Connect to Host Thread finished
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Python\python-3.4.3.amd64\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Python\python-3.4.3.amd64\lib\threading.py", line 868, in run
    self._target(_self._args, *_self._kwargs)
  File "C:\PyPipboyAppMaster\pypipboy\network.py", line 312, in _dispatchMessageLoop
    self._fireMessageEvent(msg)
  File "C:\PyPipboyAppMaster\pypipboy\network.py", line 233, in _fireMessageEvent
    listener[1](msg)
  File "C:\PyPipboyAppMaster\pypipboy\datamanager.py", line 472, in _onMessageReceived
    parser.parse(msg.payload, self._onRecordParsed)
  File "C:\PyPipboyAppMaster\pypipboy\dataparser.py", line 126, in parse
    callback(DataUpdateRecord(nodeID, valuetype, value))
  File "C:\PyPipboyAppMaster\pypipboy\datamanager.py", line 487, in _onRecordParsed
    recordExists = record.id in self._valueMap
TypeError: argument of type 'NoneType' is not iterable

**Comment by matzman666** [comment] 2015-12-30 15:40
Thx for the stack-trace. Also had this error several times, but always forgot to save the stack-trace and was not able to reproduce it. It looks like a race-condition.

**Comment by matzman666** [comment] 2015-12-30 18:29
Was a race condition in PyPipboy library. Should be fixed with the newest version.

**Closed as completed by matzman666** 2015-12-30 18:29 UTC
